import type { CoffeeItem } from "./types";

export const coffeeData: CoffeeItem[] = [
  {
    id: "1",
    name: "Espresso",
    description: "Rich and intense single shot of pure coffee",
    price: 3.5,
    category: "hot",
    image: "https://images.unsplash.com/photo-1515442261605-65987783cb6a?w=500&h=500&fit=crop",
    isPopular: true,
  },
  {
    id: "2",
    name: "Cappuccino",
    description: "Equal parts espresso, steamed milk, and milk foam",
    price: 4.75,
    category: "hot",
    image: "https://nucleuscoffee.com/cdn/shop/articles/cappuccino.jpg?v=1713632521",
    isPopular: true,
  },
  {
    id: "3",
    name: "Latte",
    description: "Espresso with steamed milk and a light layer of foam",
    price: 4.5,
    category: "hot",
    image: "https://www.nespresso.com/ncp/res/uploads/recipes/nespresso-recipes-Latte-Art-Tulip.jpg",
  },
  {
    id: "4",
    name: "Cold Brew",
    description: "Slow-steeped for 12 hours for a smooth, rich flavor",
    price: 5.25,
    category: "cold",
    image: "https://lifemadesweeter.com/wp-content/uploads/Easy-Cold-Brew-Coffee-Recipe-Vegan-Dairy-Free-Paleo-Healthy.jpg",
    isPopular: true,
  },
  {
    id: "5",
    name: "Iced Latte",
    description: "Espresso poured over ice with cold milk",
    price: 4.75,
    category: "cold",
    image: "https://www.peanutbutterandfitness.com/wp-content/uploads/2023/08/Smores-Iced-Latte-Recipe-7.jpg",
  },
  {
    id: "6",
    name: "Nitro Cold Brew",
    description: "Cold brew infused with nitrogen for a creamy texture",
    price: 5.75,
    category: "cold",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvdPZyz2qrgEKv30uJby4FDVfvDE7pP6h6Cw&s",
    isNew: true,
  },
  {
    id: "7",
    name: "Almond Croissant",
    description: "Buttery croissant filled with almond cream",
    price: 4.25,
    category: "pastry",
    image: "https://lh5.googleusercontent.com/proxy/mhkKFnZqweeTWi-xS5bmTp-jrWSJsMzX2k_LFao8BJ0ukxhaiX1Ag4nTH02nFyAHaUIwH63lv2uXaJRWLXDGS3aNFHntJbVKmJObOEDcfZFwg-uJKgOPm6n1qtH2pJFrZToR1xGeBWFhsP6moME",
    isPopular: true,
  },
  {
    id: "8",
    name: "Chocolate Muffin",
    description: "Rich chocolate muffin with chocolate chips",
    price: 3.75,
    category: "pastry",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRecEfX0hSxykk5ttSAc7JIGteTRLcxP8fK6g&s",
  },
  {
    id: "9",
    name: "Cinnamon Roll",
    description: "Freshly baked with cream cheese frosting",
    price: 4.5,
    category: "pastry",
    image: "https://tastecooking.com/wp-content/uploads/2016/01/cinnamon.jpg",
  },
  {
    id: "10",
    name: "Pumpkin Spice Latte",
    description: "Seasonal favorite with real pumpkin and spices",
    price: 5.5,
    category: "seasonal",
    image: "https://www.ambitiouskitchen.com/wp-content/uploads/2021/09/Pumpkin-Spice-Latte-4.jpg",
    isNew: true,
  },
  {
    id: "11",
    name: "Maple Pecan Latte",
    description: "Espresso with maple syrup and pecan flavoring",
    price: 5.75,
    category: "seasonal",
    image: "https://dropinblog.net/34252347/files/featured/Autumn_Bliss_Maple_Pecan_Latte.png",
    isNew: true,
  },
  {
    id: "12",
    name: "Gingerbread Latte",
    description: "Holiday spices blended with espresso and steamed milk",
    price: 5.5,
    category: "seasonal",
    image: "https://flouringkitchen.com/wp-content/uploads/2023/10/gingerbread_latte_thumbnail.jpg",
  },
];
