import type { CoffeeItem } from "./types";

export const coffeeData: CoffeeItem[] = [
  {
    id: "1",
    name: "Espresso",
    description: "Rich and intense single shot of pure coffee",
    price: 3.5,
    category: "hot",
    image: "https://source.unsplash.com/200x200/?espresso,coffee",
    isPopular: true,
  },
  {
    id: "2",
    name: "Cappuccino",
    description: "Equal parts espresso, steamed milk, and milk foam",
    price: 4.75,
    category: "hot",
    image: "https://source.unsplash.com/200x200/?cappuccino,coffee",
    isPopular: true,
  },
  {
    id: "3",
    name: "Latte",
    description: "Espresso with steamed milk and a light layer of foam",
    price: 4.5,
    category: "hot",
    image: "https://source.unsplash.com/200x200/?latte,coffee",
  },
  {
    id: "4",
    name: "Cold Brew",
    description: "Slow-steeped for 12 hours for a smooth, rich flavor",
    price: 5.25,
    category: "cold",
    image: "https://source.unsplash.com/200x200/?cold-brew,coffee",
    isPopular: true,
  },
  {
    id: "5",
    name: "Iced Latte",
    description: "Espresso poured over ice with cold milk",
    price: 4.75,
    category: "cold",
    image: "https://source.unsplash.com/200x200/?iced-latte,coffee",
  },
  {
    id: "6",
    name: "Nitro Cold Brew",
    description: "Cold brew infused with nitrogen for a creamy texture",
    price: 5.75,
    category: "cold",
    image: "https://source.unsplash.com/200x200/?nitro-coffee,coffee",
    isNew: true,
  },
  {
    id: "7",
    name: "Almond Croissant",
    description: "Buttery croissant filled with almond cream",
    price: 4.25,
    category: "pastry",
    image: "https://source.unsplash.com/200x200/?almond-croissant,pastry",
    isPopular: true,
  },
  {
    id: "8",
    name: "Chocolate Muffin",
    description: "Rich chocolate muffin with chocolate chips",
    price: 3.75,
    category: "pastry",
    image: "https://source.unsplash.com/200x200/?chocolate-muffin,pastry",
  },
  {
    id: "9",
    name: "Cinnamon Roll",
    description: "Freshly baked with cream cheese frosting",
    price: 4.5,
    category: "pastry",
    image: "https://source.unsplash.com/200x200/?cinnamon-roll,pastry",
  },
  {
    id: "10",
    name: "Pumpkin Spice Latte",
    description: "Seasonal favorite with real pumpkin and spices",
    price: 5.5,
    category: "seasonal",
    image: "https://source.unsplash.com/200x200/?pumpkin-spice-latte,coffee",
    isNew: true,
  },
  {
    id: "11",
    name: "Maple Pecan Latte",
    description: "Espresso with maple syrup and pecan flavoring",
    price: 5.75,
    category: "seasonal",
    image: "https://source.unsplash.com/200x200/?maple-pecan-latte,coffee",
    isNew: true,
  },
  {
    id: "12",
    name: "Gingerbread Latte",
    description: "Holiday spices blended with espresso and steamed milk",
    price: 5.5,
    category: "seasonal",
    image: "https://source.unsplash.com/200x200/?gingerbread-latte,coffee",
  },
];
